service: lookupnotes-api
plugins:
  - serverless-dynamodb-local
custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${opt:stage, self:provider.stage}-docs
  dynamodb:
    stages:
      - dev
    start:
      port: 8888
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      test:
        sources:
          - table: ${self:custom.tableName}
            sources: [./test-docs.json]
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 30
  environment: 
    APP_ENV: ${self:custom.stage}
functions:
  app:
    handler: lambda-index.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
resources:
  Resources:
    DocsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        TableName: ${self:custom.tableName}